eu:
  nameOverride: elera-platform
  elera_common:
    dockerRegistry:
      repository: 
      imagePullSecrets:
        - name: 

  elera_ingress:
    enabled: false

  elera_services:
    elera_admin_ui:
      image: elera-platform-admin-ui-all-eu
      imageTag: 1.19.0

    elera_platform:
      image: platform
      imageTag: 1.19.0
      imageLayered: true
      readinessProbe:
        initialDelaySeconds: 60
      command:
        extraArguments:
          - mock.gateways=true
          - tgcp.mock.shipping=true

    elera_client:
      image: elera-client
      imageTag: 0.18.0
      enabled: true
      extraNginxConf:
        endOfServerSection: |
          # Add missing authorization entries
          location /authorization/alternateLogin {
            proxy_pass      
          }
          location /authorization/config {
            proxy_pass      
          }

  elera_nginx:
    image: elera-client-nginx
    imageTag: 1.4.0
    disableLoadBalancer: true

  data_loader:
    enabled: false
    image: data-loader
    imageTag: 1.19.0
    imageLayered: false
    command:
      extraArguments:
        - cache.refresh=false
        - data-seeder.sets=elera/base-eu,colruyt/colruyt/base,elera/demo-eu/elera-pay,elera/demo-eu/receipt,colruyt/colruyt/demo
        - changeplans.service=elera-platform-elera-platform
        - changeplans.port=8080
