name: Get current image versions

on:
  push:
    branches:
      - main  # Adjust the branch name to match your main branch
  schedule:
    # runs tests every day at 4am
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-22.04
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: set execute permission on ./getcurrentversions.sh
        run: |
          chmod +x ./getcurrentversions.sh
      - name: Run the script
        run: |
          bash -e ./getcurrentversions.sh
